### ISSUE TITLE
Can't start Vagrant KVM on Ubuntu 14.04 w/ Vagrant 1.6.5

### ISSUE THREAD

**Issue by mhamann** [adrahon/vagrant-kvm#256]
Getting the following error when running `vagrant up`:

```
$ vagrant up
~/.vagrant.d/gems/gems/vagrant-kvm-0.1.8/lib/vagrant-kvm/driver/driver.rb:735:in `capabilities': Expected Connection object (ArgumentError)
    from ~/.vagrant.d/gems/gems/vagrant-kvm-0.1.8/lib/vagrant-kvm/driver/driver.rb:735:in `connect_libvirt_qemu!'
    from ~/.vagrant.d/gems/gems/vagrant-kvm-0.1.8/lib/vagrant-kvm/driver/driver.rb:44:in `initialize'
    from ~/.vagrant.d/gems/gems/vagrant-kvm-0.1.8/lib/vagrant-kvm/provider.rb:34:in `new'
    from ~/.vagrant.d/gems/gems/vagrant-kvm-0.1.8/lib/vagrant-kvm/provider.rb:34:in `machine_id_changed'
    from ~/.vagrant.d/gems/gems/vagrant-kvm-0.1.8/lib/vagrant-kvm/provider.rb:15:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:127:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:127:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/vagrantfile.rb:75:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/vagrantfile.rb:75:in `machine'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:537:in `machine'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:192:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:174:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/up/command.rb:67:in `block in execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:268:in `block (2 levels) in batch'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:266:in `tap'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:266:in `block in batch'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:265:in `synchronize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:265:in `batch'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/commands/up/command.rb:58:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:292:in `cli'
    from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant:174:in `<main>'
```

**Comment by hmehra** [comment]
Have the same problem. This is the backtrace -
[human:'src'] vagrant up --provider=libvirt
Bringing machine 'default' up with 'libvirt' provider...
/home/hmehra/.vagrant.d/gems/gems/fog-1.28.0/lib/fog/libvirt/requests/compute/list_domains.rb:13:in `list_defined_domains': Expected Connection object (ArgumentError)
	from /home/hmehra/.vagrant.d/gems/gems/fog-1.28.0/lib/fog/libvirt/requests/compute/list_domains.rb:13:in `list_domains'
	from /home/hmehra/.vagrant.d/gems/gems/fog-1.28.0/lib/fog/libvirt/models/compute/servers.rb:11:in `all'
	from /home/hmehra/.vagrant.d/gems/gems/vagrant-libvirt-0.0.25/lib/vagrant-libvirt/action/set_name_of_domain.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/hmehra/.vagrant.d/gems/gems/vagrant-libvirt-0.0.25/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by adrahon** [comment]
@hmehra you meant to report this as a vagrant-libvirt issue, I think? https://github.com/pradels/vagrant-libvirt/
