### ISSUE TITLE
trusty box gives 404

### ISSUE THREAD

**Issue by fsouza** [adrahon/vagrant-kvm#277]
The link from the Wiki gives 404: https://vagrant-kvm-boxes-si.s3.amazonaws.com/trusty64-kvm-20140418.box.

It reports that the bucket doesn't exist. If I change it to just vagrant-kvm-boxes (removing the si), it doesn't report that the bucket doesn't exist, but it does return 403.

Can you provide an up-to-date link for the trusty64 box?

**Comment by fsouza** [comment]
Just found the right link and updated the Wiki, sorry for the noise.

**Comment by adrahon** [comment]
Great! Also, this project is dead and chances are you want https://github.com/pradels/vagrant-libvirt instead :)
